### ISSUE TITLE
Add support for --cap-add and --cap-remove flag

### ISSUE THREAD

**Issue by peterabbott** [portertech/kitchen-docker#104]
In order to run some services, for example tomcat on ubuntu, a container requires the capability SYS_PTRACE, others the init.d daemon startup will fail. 

Discovered this while writing some test kitchen serverspec tests and switched from vagrant to docker driver and the tests started failing.

**Comment by jaydubbyasee** [comment]
I've been running into this as well. As an unsafe workaround, you can enable privileged mode.

**Comment by steffengodskesen** [comment]
I'm also running into this with some of our tests. Lately with the postfix init script from Debian wheezy which tries to read /proc/PID/exe.

Running the container in privileged mode sure works, but apart from the security issues with that, I often also run into this Docker behaviour: https://github.com/docker/docker/issues/4040. 

Being able to --cap-add=SYS_PTRACE would sure make my world a happier place.

**Comment by peterabbott** [comment]
Got tired of waiting for a response from repo owner so I have forked this and published a new driver with this fix included. When we do get a response I'll look at merging back.

New Gem: https://rubygems.org/gems/kitchen-docker_ssh

Refer: https://github.com/portertech/kitchen-docker/issues/112#issuecomment-87333727

**Comment by miketheman** [comment]
https://github.com/portertech/kitchen-docker/pull/105 has been emrged & released - recommend closure.

**Comment by coderanger** [comment]
Thanky!
