### ISSUE TITLE
ssh to kitchen docker with no need to input password

### ISSUE THREAD

**Issue by DennyZhang** [portertech/kitchen-docker#110]
Forgive me, if it's a solved problem.

Each time I run "kitchen login" to docker container, I will have to input password of "kitchen" manually.
Is there a supported way to inject my ssh key to docker container, to avoid this?

I can wrap this by playing with provision_command, but it would be a little ugly.

**Comment by peterabbott** [comment]
You'd have to update the driver to put the ssh key in the correct location. This is what other drivers do.

**Comment by miroswan** [comment]
I have a PR for this: https://github.com/portertech/kitchen-docker/pull/141/

**Comment by miroswan** [comment]
I think this one can be closed.

**Comment by coderanger** [comment]
Thanky!
