### ISSUE TITLE
Binary option on OSX doesn't seem to work.

### ISSUE THREAD

**Issue by myappleguy** [portertech/kitchen-docker#155]
Docker is installed with brew and the cli docker tool works fine.
I tried without the binary option because docker is in the path and works,
but that renders the same error.
I pass it the path in the binary option but it still doesn't work.

```
~/code/reaperbot-web-cookbook (master ✘)✹ ᐅ which docker
/usr/local/bin/docker
~/code/reaperbot-web-cookbook (master ✘)✹ ᐅ docker --version
Docker version 1.7.1, build 786b29d
~/code/reaperbot-web-cookbook (master ✘)✹ ᐅ cat .kitchen.yml | grep -A 6 docker-centos
  - name: docker-centos-7.0
    driver_config:
      image: centos:7.0
      platform: centos
    driver:
      name: docker
      binary: /usr/local/bin/docker
~/code/reaperbot-web-cookbook (master ✘)✹ ᐅ kitchen list
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: You must first install the Docker CLI tool http://www.docker.io/gettingstarted/
>>>>>> ----------------------
```

**Comment by peterabbott** [comment]
Do you have the DOCKER_HOST and other env variables docker cli needs set?

**Comment by myappleguy** [comment]
@peterabbott  I don't, could you point me to the documentation for those env variables?

**Comment by peterabbott** [comment]
It is mentioned here: https://github.com/portertech/kitchen-docker#socket 

But assuming you are running boot2docker or docker machine, it should tell you when you start the process what variables need setting.

```
$ boot2docker shellinit
```

**Comment by coderanger** [comment]
The problem is your config, it should look like this:

```yaml
  - name: docker-centos-7.0
    driver_config:
      name: docker
      image: centos:7.0
      platform: centos
      binary: /usr/local/bin/docker
```

You can always `kitchen diagnose` to see the compiled config data for each instance.
