### ISSUE TITLE
zlib(finalizer): stream was freed prematurely

### ISSUE THREAD

**Issue by st-isidore-de-seville** [portertech/kitchen-docker#162]
Hello.  I do not know if this belongs here but figured it would be a start.  Whenever I run kitchen-docker, I receive an message that states "zlib(finalizer): stream was freed prematurely" but the testing does exist successfully.  

I am not sure if this is a problem but figured I would create the issue just in case.

Thanks!

**Comment by ccasey** [comment]
-----> Kitchen is finished. (1m43.11s)
zlib(finalizer): the stream was freed prematurely.

**Comment by coderanger** [comment]
This is a core Test Kitchen issue related to the recent net-ssh fixes. It is probably harmless though.

**Comment by st-isidore-de-seville** [comment]
Thanks @ccasey & @coderanger!
