### ISSUE TITLE
When creating the dockerfile, you should be able to pass environment variables to the file

### ISSUE THREAD

**Issue by proffalken** [portertech/kitchen-docker#164]
For various reasons, I need to be able to pass the ENV parameter into the Dockerfile created by kitchen docker in order to get SystemD running as outlined at https://rhatdan.wordpress.com/2014/04/30/running-systemd-within-a-docker-container/

It would be good to see the option to provide ENV along side the current RUN and CMD sections of the file.

**Comment by coderanger** [comment]
Probably overkill to support this via the Yaml, just provide your own Dockerfile template.

**Comment by proffalken** [comment]
In my use-case you're probably right, however assuming that people still develop 12-factor applications or similar and want to test those here too, I suspect setting the ENV in the default config would be useful.

More than anything else, I didn't want to have to replicate the majority of the default Dockerfile as a template when I only really want to change a couple of lines! :)

**Comment by proffalken** [comment]
Closing, no longer required.
