### ISSUE TITLE
rhel fails on command yum clean all

### ISSUE THREAD

**Issue by bbaugher** [portertech/kitchen-docker#168]
When I run kitchen-docker with `rhel` I get,

<pre><code>
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of docker -H tcp://192.168.59.103:2376 build -f cookbook/Dockerfile-kitchen-20151007-26191-6yi628 - ----
STDOUT: Sending build context to Docker daemon 3.072 kB
Sending build context to Docker daemon
Step 0 : FROM rhel
 ---> 82ad5fa11820
Step 1 : RUN yum clean all
 ---> Running in 2c00013bc65e
Loaded plugins: product-id, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
There are no enabled repos.
 Run "yum repolist all" to see the repos you have.
 You can enable repos with yum-config-manager --enable <repo>
</code></pre>

Here are my versions,

    chef --version
    Chef Development Kit Version: 0.7.0
    chef-client version: 12.4.1
    berks version: 3.2.4
    kitchen version: 1.4.2
    
    chef gem list | grep docker
    kitchen-docker (2.3.0)

**Comment by coderanger** [comment]
Would you expect it to automatically use your subscription info? Generally people would use CentOS for testing instead.

**Comment by bbaugher** [comment]
This is a good point now that I think about it. I'm trying to switch from testing using kitchen-vagrant to kitchen-docker but I think I would need to create my own docker images which point to our internal RHEL repos. I guess I forgot RHEL doesn't provide these basic repos.

Feel free to close
