### ISSUE TITLE
RHEL docker images in .kitchen.yml file

### ISSUE THREAD

**Issue by jlanado** [portertech/kitchen-docker#178]
I pulled these rhel images manually using docker pull

REPOSITORY                                               TAG             IMAGE ID              CREATED             VIRTUAL SIZE
registry.access.redhat.com/rhel                   latest           c4f590bbcbe3        2 weeks ago         158.2 MB
registry.access.redhat.com/rhel7.2              latest           58958c7fafb7        11 weeks ago       201.6 MB

and wanted to put these in my .kitchen.yml file, how do I call these images from the platforms block, say if I want to use rhel 7.2?

---
driver:
name: docker
use_sudo: false

provisioner:
name: chef_zero

platforms:
- name: ? <--- need input on this

suites:
- name: default
run_list:
attributes:
 
I appreciate the help.

**Comment by st-isidore-de-seville** [comment]
This should help as I asked the same question: https://github.com/portertech/kitchen-docker/issues/177

**Comment by trinitronx** [comment]
The [default image name is derived here][1].  So for instance, if I had this in my `.kitchen.docker.local.yml` file:

```yaml
platforms:
## Trusty Tahr LTS
- name: ubuntu-14.04
## Vivid Vervet ## EOL January 2016
- name: ubuntu-15.04
## Xenial Xerus
- name: ubuntu-16.04
```

Then, the derived image names would be:

```yaml
ubuntu:14.04
ubuntu:15.04
ubuntu:16.04
```

You'll notice the only special case handled here is `centos`, which discards the minor version to derive the docker image label.

Check the official Docker Hub images for the supported & labeled versions:

 - [CentOS](https://hub.docker.com/_/centos/)
 - [Ubuntu](https://hub.docker.com/_/ubuntu/)

Surprisingly there are no "Official" RHEL images, however a search on Docker Hub returns many community supported images:

 - [RedHat](https://hub.docker.com/search/?q=redhat&page=1&isAutomated=0&isOfficial=0&starCount=0&pullCount=0)

[1]: https://github.com/portertech/kitchen-docker/blob/master/lib/kitchen/driver/docker.rb#L89-L99

**Comment by coderanger** [comment]
This is documented in the readme, you can put whatever you want for the platform name and then override the `image` setting to be any image name docker can process. https://github.com/portertech/kitchen-docker#installation-and-setup

As mentioned above, there are no RHEL Docker images because running RHEL requires a subscription. Testing against CentOS is usually preferable, depending on what you are testing.

**Comment by tyrken** [comment]
N.B. For any other peeps who end up here, the correct platform value is 'rhel', not 'redhat'.  But see #128 which might halt you again.
