### ISSUE TITLE
Different color for stdout than ie in kitchen-vagrant

### ISSUE THREAD

**Issue by alexanderadam** [portertech/kitchen-docker#180]
Somehow standard console output is yellow like it would typically be for warnings.
In `kitchen-vagrant` it's also colored but green (like for a successful operation).

I don't want to be nit-picked but as colors usually also have a semantic meaning in build and test runs I currently don't know wether it is a bug in my configuration or perhaps something in `kitchen-docker`.

In this case I am even unsure which configuration files or other information could be relevant so let me know if you need something. I didn't even found something in the `kitchen-docker` source regarding colors but something seems to be different here. :wink: 

IMHO it could also be the standard terminal text color so it wouldn't be any mixing when runnings in combination with specs. So either consistent with `kitchen-vagrant` or standard color would probably be useful.

**Comment by alexanderadam** [comment]
Sorry but today everything is fine on my system so nevermind. Probably an issue on my system.

**Comment by coderanger** [comment]
Color in Kitchen comes from which instance you are using, following a standard order.
