### ISSUE TITLE
[Confused] remote_file create new file everytime.

### ISSUE THREAD

**Issue by chrisduong** [portertech/kitchen-docker#200]
Hi, 

I have no such problem with `kitchen-vagrant`, but if I use `kitchen-docker`, I saw Chef **remote_file** has to do the download everytime even if it had already downloaded the file.

In the recipe `rabbitmq::default`, which describes remote_file RabbitMQ package.

```ruby
remote_file "#{Chef::Config[:file_cache_path]}/#{node['rabbitmq']['deb_package']}" do
      source deb_package
      action :create_if_missing
end
```

I checked the console log, and I saw that every `kitchen converge` will delete the file, and download the file again. I'm not sure if it is **Docker's issue or not**.

This is the second run log of `kitchen converge` after the first successful run.
```
Recipe: rabbitmq::default
         * dpkg_autostart[rabbitmq-server] action nothing (skipped due to action :nothing)

         * remote_file[/tmp/kitchen/cache/rabbitmq-server_3.6.1-1_all.deb] action create_if_missing
           - create new file /tmp/kitchen/cache/rabbitmq-server_3.6.1-1_all.deb
           - update content in file /tmp/kitchen/cache/rabbitmq-server_3.6.1-1_all.deb from none to 0728fb
           (new content is binary, diff output suppressed)
```

**Comment by eiser82** [comment]
@chrisduong Assuming that every time you run `kitchen converge` a new docker container is created, the behavior you just described sounds good to me. In `kitchen-vagrant` the VM stays up and running until you `kitchen destroy` it, meaning files and any changes made after the `kitchen converge` will be conserved, making a good and fast way to test small changes while you work on them. With docker, a new container is created every time, making chef run with a clean image. It's up to you to choose the one that fits your needs.

**Comment by coderanger** [comment]
@eiser82 That isn't how the plugin works, life cycle management is the same for all Kitchen drivers.

@chrisduong This is probably because Test Kitchen puts the file cache path in a different place than usual, and depending on your exact setup it can get wiped each run. Check out the `kitchen-sync` plugin if this becomes a problem.
