### ISSUE TITLE
Using with native Docker for Mac client

### ISSUE THREAD

**Issue by peterabbott** [portertech/kitchen-docker#201]
In case anybody else gets stuck with this. 

There is an issue with the verify_dependencies check when using the new native Docker Mac client. 

A workaround is to add `use_sudo: false` (if not already there) to your kitchen.yml driver config. 

The cause is in the startup when the driver is created there is a default of setting use_sudo to true when using a local socket. 
```
  default_config :use_sudo do |driver|
        !driver.remote_socket?
      end

```

**Comment by cassianoleal** [comment]
Did you manage to work around it trying to SSH to localhost?

**Comment by peterabbott** [comment]
I think it is because the driver currently determines the IP address from the `remote_socket` instead of perhaps using the `docker inspect ` command.

The issue is that the default ssh host set in the driver, it defaults to localhost if remote_socket not set, 
https://github.com/portertech/kitchen-docker/blob/master/lib/kitchen/driver/docker.rb#L108

A workaround is updating the network setting, I guess use it with caution as it would expose any containers to the external interfaces.
```
  pinata set network nat external-bind=true
```

If I get a chance I'll do a PR to fix these issues.

**Comment by cassianoleal** [comment]
Cool. I should have mentioned though, after I posted the question I found out that enabling "VPN Compatibility Mode" in Docker's preferences is a suitable workaround.

I didn't dig into how that works but somehow it exposes the containers' ports as though they were on the host, effectively allowing `kitchen-docker` to SSH to `localhost`.

Is this the same as running the `pinata` command perhaps, or they just produce similar results?

**Comment by peterabbott** [comment]
Probably does the same under the hood. 

Even with VPN Compatibility mode I've not been able to get it working behind our corporate proxy because it does not allow self-signed certs like docker-machine does. But that is not for this project.

**Comment by cassianoleal** [comment]
This doesn't seem to work on Version 1.11.0-beta8 (build: 6072).

I tried enabling VPN compat on the UI and it doesn't seem to change anything.

Running `pinata` on the terminal errors out:

```
pinata: network nat does not have a valid subkey 'external-bind'
```

Any ideas?

**Comment by peterabbott** [comment]
Beta8 is quite buggy, I am not able to run anything with it that requires ssh access

**Comment by coderanger** [comment]
Going to leave this open for tracking, but I'm not going to make any serious efforts towards support until it's out of beta :)

**Comment by peterabbott** [comment]
Cool, I created more as a notice for others in case they see similar behaviour and document workarounds. You could probably close and we can still comment on it as things come up if you'd prefer

**Comment by cassianoleal** [comment]
```
pinata set native/port-forwarding true
```

seems to solve the issue. I'm able to use test-kitchen again! :)

In case anyone else tries this and fails, I had reset to factory defaults before I ran the command. I wish I had tried it before resetting but I only found out about the command after that.

**Comment by peterabbott** [comment]
This just came up in the release notes for beat version 9 that just popped up on my machine, don't have time right now to test but might help

```
localhost is now used for port forwarding by default. docker.local will no longer work as of Beta 9. See documentation for details.
```

**Comment by cassianoleal** [comment]
Yes, it looks like `native/port-forwarding` is `true` by default now. Beta 9 is looking good to me.

**Comment by peterabbott** [comment]
Beta 9 is a big improvement, it appears to even work behind corporate proxy with a self-signed cert.

**Comment by SydOps** [comment]
So the work around is:

1. active `port-forwarding`

    pinata set network nat external-bind=true

2. add `use_sudo: false`  to your kitchen.yml driver config:

    driver:
      name: docker
      use_sudo: false

**Comment by SydOps** [comment]
Ok, my problem is related to the mac system upgrade to 10.11.5 which I got prompt by system and upgraded yesterday night

https://forums.docker.com/t/cant-find-docker-sock-after-system-upgrade-to-10-11-5/13323

**Comment by cassianoleal** [comment]
I've been running `beta12` on OS X `10.11.5` for a few weeks with no problems whatsoever.

No need for workarounds or custom settings anywhere.

**Comment by SydOps** [comment]
@cassianoleal 

The problem is not for all 10.11.5 users, I have it and have to deal with it. 

Another solution is, if you re-install native docker, you will not see the issue.

**Comment by cassianoleal** [comment]
@SydOps I never meant to say no one is having to deal with this issue. Just chiming in to say that it's not a general issue.

You mentioned re-installing Docker, which I don't think I did, but I recall resetting it to factory defaults at one point.

**Comment by SydOps** [comment]
Seems in latest native docker, command `pinata` has been removed.

 https://forums.docker.com/t/pinata-missing-in-latest-mac-beta-1-11-2-beta15/15541

**Comment by preillyme** [comment]
👎

**Comment by joestump** [comment]
Confirmed that `use_sudo: false` solves issues related to Docker on Kitchen. I also did a restore to factory defaults, but I'm not sure this resolved the actual issue.
