### ISSUE TITLE
kitchen converge fails behind proxy

### ISSUE THREAD

**Issue by schuster-rainer** [portertech/kitchen-docker#72]
If configured my driver with the proxy settings. But converging the image fails because the proxy settings are only used for executing commands but not in the Dockerfile itself, which kitchen-docker creates. The build_dockerfile method doesn't use the proxy. Therefore the apt-get update fails ... I'd suggest to rewrite this step be be issued as a command, once the docker image has been built. The problem here is if I'm going to include the proxy in the Dockerfile this image only works with this proxy. That's the reason all RUN commands have to be executed after the image has been converged and must not be part of the Dockerfile itself.

**Comment by andrewshawcare** [comment]
In order to make this work correctly, I copied the Dockerfile-kitchen file that was created and manually injected my proxy information, as such:

```Dockerfile
FROM ubuntu:14.04
RUN dpkg-divert --local --rename --add /sbin/initctl
RUN ln -sf /bin/true /sbin/initctl
ENV DEBIAN_FRONTEND noninteractive
ENV http_proxy 'http://proxy.example.com:80'
ENV https_proxy 'https://proxy.example.com:443'
ENV HTTP_PROXY 'http://proxy.example.com:80'
ENV HTTPS_PROXY 'https://proxy.example.com:443'
RUN apt-get update
RUN apt-get install -y sudo openssh-server curl lsb-release

RUN if ! getent passwd kitchen; then useradd -d /home/kitchen -m -s /bin/bash kitchen; fi
RUN echo kitchen:kitchen | chpasswd
RUN echo 'kitchen ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
RUN mkdir -p /etc/sudoers.d
RUN echo 'kitchen ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/kitchen
RUN chmod 0440 /etc/sudoers.d/kitchen
RUN [ ! -d /home/kitchen/.ssh ] && mkdir /home/kitchen/.ssh
RUN chown -R kitchen /home/kitchen/.ssh
RUN chmod 0700 /home/kitchen/.ssh
RUN echo 'ssh-rsa REDACTED_SSH_KEY kitchen_docker_key' >> /home/kitchen/.ssh/authorized_keys
RUN chown kitchen /home/kitchen/.ssh/authorized_keys
RUN chmod 0600 /home/kitchen/.ssh/authorized_keys
```

I then referenced the file, `Dockerfile-kitchen` in my `driver-config` property of `.kitchen.yml`:

```YAML
...
driver_config:
  http_proxy: <%= ENV['http_proxy'] %>
  https_proxy: <%= ENV['https_proxy'] %>
  use_sudo: false
  remove_images: true
  dockerfile: Dockerfile-kitchen
...
```
