### ISSUE TITLE
kitchen login prompts for password

### ISSUE THREAD

**Issue by miketheman** [portertech/kitchen-docker#81]
I've tried to figure out what's not moving along correctly, and finally threw my hands up in the air at my own inability to grok this, so here I am asking about it.

Most kitchen drivers provide the user/name and password, so that you don't have to type a password. kitchen-vagrant handles this correctly.

With kitchen-docker, I must type in the default password any time I want to log in.

I can see that there's a setting for username/password [in the code](https://github.com/portertech/kitchen-docker/blob/d21213a98f0d12be29d8f7c784aee026951e6221/lib/kitchen/driver/docker.rb#L37-L38) and this user/password combo does indeed work, since the `kitchen setup/converge/verify/test` all work over ssh, right?

```
$ kitchen login -l debug source-ubuntu-1204
D      [kitchen::driver::docker command] BEGIN (docker > /dev/null)
D      [kitchen::driver::docker command] END (0m0.00s)
D      Berksfile found at /Users/miketheman/code/miketheman/nginx/Berksfile, loading Berkshelf
D      Berkshelf 3.1.5 library loaded
D      Login command: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=VERBOSE -p 49156 kitchen@192.168.42.43 (Options: {})
Warning: Permanently added '[192.168.42.43]:49156' (RSA) to the list of known hosts.
kitchen@192.168.42.43's password:
Authenticated to 192.168.42.43 ([192.168.42.43]:49156).
Last login: Sat Sep  6 14:59:15 2014 from 192.168.42.1
kitchen@3b5d8f92de41:~$
```

Related gems:
- kitchen-docker (1.5.0)
- test-kitchen (1.2.1)

My .kitchen.local.yml:
```
driver:
  name: docker
  socket: tcp://192.168.42.43:2375 # boot2docker
```

And now I don't know where else to look.

**Comment by miketheman** [comment]
@portertech Have you had a chance to read this? With the recent changes to the lib, I haven't had a chance to see if I can dig through to trace the behavior, but I can confirm that a `kitchen login` still prompts the user for a password.

**Comment by jerroydmoore** [comment]
+1 for experiencing this problem.

**Comment by shaneramey** [comment]
I'm also having this issue. Here's a workaround command-line Expect script:

`expect -c 'spawn kitchen login; expect "ssword: "; send -- "kitchen\r"; interact'`

**Comment by jeffbyrnes** [comment]
This was fixed in #141, and released in [v2.3.0](https://github.com/portertech/kitchen-docker/releases/tag/v2.3.0).

**Comment by petere** [comment]
I can confirm that I had this issue with 1.5.0 but no longer with 2.3.0.

**Comment by coderanger** [comment]
Yep, closing this out now that this is no longer an issue.

**Comment by amaltson** [comment]
Thanks for getting this in, super useful! :+1:
