### ISSUE TITLE
fedora platform not supported

### ISSUE THREAD

**Issue by miketheman** [portertech/kitchen-docker#84]
Probably needs to be placed [in here](https://github.com/portertech/kitchen-docker/blob/d21213a98f0d12be29d8f7c784aee026951e6221/lib/kitchen/driver/docker.rb#L117-L145).

Looks like ti might be legit: https://registry.hub.docker.com/_/fedora/tags/manage/

**Comment by portertech** [comment]
master has "fedora" as a platform choice ;)
