### ISSUE TITLE
getting docker usage output when running kitchen command

### ISSUE THREAD

**Issue by odedpr** [portertech/kitchen-docker#90]
Hi, 
I don't know when it started but now there is an annoying bug,

Whenever I run kitchen with a subcommand, I get the docker usage in the output.

![image](https://cloud.githubusercontent.com/assets/4990615/5009653/5bec34d4-6a72-11e4-9ce5-3e0d5c3f3488.png)

![image](https://cloud.githubusercontent.com/assets/4990615/5009656/638f9e74-6a72-11e4-9908-e9b80bb0b790.png)

**Comment by portertech** [comment]
master now redirecting both stderr and stdout to /dev/null.
